import os

CASSANDRA_CONTACT_POINTS = os.getenv("CASSANDRA_CONTACT_POINTS", "localhost")
CASSANDRA_PORT = int(os.getenv("CASSANDRA_PORT", 9042))
CASSANDRA_KEYSPACE = os.getenv("CASSANDRA_KEYSPACE", "jotun_lair")
REPLICATION_FACTOR = int(os.getenv("CASSANDRA_REPLICATION_FACTOR", 3))