version: '3.8'

services:
  # Bases de datos
  neo4j:
    build:
      context: ./
      dockerfile: ./databases/neo4j/Dockerfile
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_default__listen__address=0.0.0.0  # Nuevo
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687 # Nuevo
      - NEO4J_server_bolt_advertised__address=0.0.0.0:7687 # Nuevo
    healthcheck: # Añadir healthcheck
      test: ["CMD", "nc", "-zv", "localhost", "7687"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:  # Añadir red
      - jotun-network

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - ./databases/cassandra/data:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./databases/mongodb/data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=jotun_wiki

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"  # Redis core
      - "8001:8001"  # RedisInsight
    volumes:
      - ./databases/redis/data:/data

  # Servicios de aplicación
  editor-service:
    build: ./services/editor-service
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - ./services/editor-service:/app
      - /app/node_modules
    networks:
      - jotun-network

  leaderboard-service:
    build: ./services/leaderboard-service
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=jotun_lair
      - CASSANDRA_REPLICATION_FACTOR=3
    volumes:
      - ./services/leaderboard-service:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  wiki-service:
    build: ./services/wiki-service
    depends_on:
      - mongodb
    ports:
      - "8083:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/jotun_wiki
    volumes:
      - ./services/wiki-service:/app
      - /app/node_modules

  avatar-service:
    build: ./services/avatar-service
    depends_on:
      - redis
    ports:
      - "8084:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOAD_AVATARS_ON_STARTUP=true
      - METADATA_FILE=/app/assets/metadata.json
    volumes:
      - ./services/avatar-service:/app
      - ./assets/avatars:/app/assets/avatars
      - ./assets:/app/assets
      - /app/node_modules

  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - editor-service
      - leaderboard-service
      - wiki-service
      - avatar-service
    environment:
      - EDITOR_SERVICE_URL=http://editor-service:8080
      - LEADERBOARD_SERVICE_URL=http://leaderboard-service:8080
      - WIKI_SERVICE_URL=http://wiki-service:8080
      - AVATAR_SERVICE_URL=http://avatar-service:8080
      - JWT_SECRET=your-secret-key
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules

volumes:
  neo4j_data:
  cassandra_data:
  mongo_data:
  redis_data:
  
networks:
  jotun-network:
    driver: bridge
